builds:
  -
    ldflags: -s -w -X github.com/bpineau/kube-deployments-notifier/cmd.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64

release:
  # don't autopublish
  draft: true

dockers:
  -
    image: bpineau/kube-deployments-notifier
    goos: linux
    goarch: amd64
    latest: true
    dockerfile: Dockerfile.goreleaser
