name: release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  goreleaser:
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Unshallow
      run: |
          git fetch --prune --unshallow || true

    - name: Log into Docker registry
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: v0.123.3
        args: release --rm-dist --skip-sign
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
